### PR TITLE
Fix http2.inl: C11 strict mode compliance and LTO multiple-definition errors

### PR DESCRIPTION
**Pull request by morgonf**
## Summary

Two portability fixes in `src/http2.inl`:

**1. `DEBUG_TRACE` calls with no format arguments break strict C11**

```c
// Before
DEBUG_TRACE("HTTP2 key decoding error");

// After
DEBUG_TRACE("%s", "HTTP2 key decoding error");
```

`DEBUG_TRACE` is a variadic macro. Calling it with a single string and no `...` arguments relies on the GNU `##__VA_ARGS__` extension to swallow the trailing comma. This extension is not available in `-std=c11` / `-pedantic-errors` mode, causing a hard compilation error. The fix passes the string as an argument to an explicit `%s` format, which is valid in all C standards.

**2. Non-static file-scope variables cause LTO link errors**

Five variables — `hpack_huff_dec`, `hpack_huff_end_code`, `hpack_huff_start_index`, `http2_default_settings`, `http2_civetweb_server_settings` — were defined at file scope without `static`. Because `http2.inl` is included from multiple translation units during link-time optimization, the linker sees multiple definitions of the same symbol and raises an error. Adding `static` gives each TU its own copy, which is the correct semantics for `inl` files.

## Test plan

- [ ] Build with `-std=c11 -pedantic-errors` and confirm no diagnostic on `DEBUG_TRACE` lines.
- [ ] Build with LTO (`-flto`) enabled and confirm no multiple-definition linker errors.

### CODE REVIEW

**Comment by morgonf** [comment]
The CI failures here are caused by a pre-existing compilation error in `master` introduced by commit 588860e (CVE-2025-55763): a missing parenthesis in the `if` condition and an undeclared variable `cl` in `get_request()`. This breaks all GCC and clang builds regardless of what a PR changes. PR #1399 fixes it.
