### PR TITLE
Fix dead null check in interpret_uri and use-after-free in set_ports_option

### PR DESCRIPTION
**Pull request by morgonf**
## Summary

Two memory-safety bugs found via static analysis:

**1. Dead null guard in `interpret_uri()` (`src/civetweb.c`)**

`filestat` is always non-null at this point — it is passed in by callers and already dereferenced unconditionally via `memset()` earlier in the same call. The `if (filestat)` check before setting `filestat->is_gzipped` was therefore unreachable dead code, not a real null-safety guard. Removing it makes the intent clear.

**2. Use-after-free in `set_ports_option()` (`src/civetweb.c`)**

When the second `mg_realloc_ctx()` call fails, the original code called `mg_free(ptr)` and continued the loop. But the first realloc had already moved `phys_ctx->listening_sockets` to the new address stored in `ptr`. Freeing `ptr` and not updating `listening_sockets` left a dangling pointer, causing a use-after-free on the next loop iteration and inside `close_all_listening_sockets()`.

The fix stores `ptr` back into `phys_ctx->listening_sockets` before skipping the failed socket, which keeps the already-allocated array reachable.

## Test plan

- [ ] Build with `-fsanitize=address` and run the test suite — neither change should affect normal execution, but the use-after-free fix prevents UBSan/ASan from flagging the error path in `set_ports_option`.
- [ ] Review that no caller of `interpret_uri()` ever passes a null `filestat` (they don't — all callers pass a local `struct mg_file_stat`).

### CODE REVIEW

**Comment by morgonf** [comment]
The CI failures here are caused by a pre-existing compilation error in `master` introduced by commit 588860e (CVE-2025-55763): a missing parenthesis in the `if` condition and an undeclared variable `cl` in `get_request()`. This breaks all GCC and clang builds regardless of what a PR changes. PR #1399 fixes it.

**Review by DL6ER — APPROVED** [review]
Both changes look right to us: `filestat` cannot be `NULL` at that point, as `mg_stat()` would already have dereferenced it, and `ptr` is the *successful* realloc result, so freeing it while `phys_ctx->listening_sockets` still holds the old block leaves a dangling pointer for the cleanup path - the assignment matches what the success path does a few lines further down.

We have inherited this patch into the `pi-hole` branch of DL6ER/civetweb, our own mirror for as long as master is not moving here.
