### ISSUE TITLE
USE_X_DOM_SOCKET fails on FreeBSD

### ISSUE THREAD

**Issue by SirHumphreyAppleby** [civetweb/civetweb#1017]
Civetweb fails to compile on FreeBSD using the USE_X_DOM_SOCKET compile option. This feature appears to be under development (incomplete implementation in 1.14), so I'm just raising this as an issue for now and may look at it in more detail in the future if somebody doesn't beat me to it.

.../src/civetweb.c:8971:29: error: no member named 'lsa' in 'union usa'
                if (hostlen >= sizeof(sa->lsa.sun.sun_path)) {
                                      ~~  ^
.../src/civetweb.c:9025:42: error: no member named 'lsa' in 'union usa'
                memset(sa->sun.sun_path, 0, sizeof(sa->lsa.sun.sun_path));

**Comment by bel2125** [comment]
The current head version should fully support USE_X_DOM_SOCKET for Linux.
I did not test this on FreeBSD, I don't have a test system with FreeBSD.

Maybe something is missing for FreeBSD, but most likely it is just something small (some additional define or include, ...).
If plan to have a look at this for FreeBSD and provide a pull request, I will be happy to merge it.

**Comment by SirHumphreyAppleby** [comment]
I assumed this worked in Linux in 1.14 and this was a platform-specific issue. This issue has been fixed in head...

https://github.com/civetweb/civetweb/commit/4aee4ea66135f000f3f7c11f35192328d4466005
