### ISSUE TITLE
can not build with lua 5.1

### ISSUE THREAD

**Issue by laoshaw** [civetweb/civetweb#949]
for lua5.1 I got below errors on ubuntu 20.04, lua5.2 and lua5.3 built fine

```
make WITH_LUA_VERSION=501 WITH_WEBSOCKET=1 WITH_SERVER_STATS=1 WITH_ZLIB=1 WITH_LUA_SHARED=1
Lua: Using version 5.1.5
Lua: using dynamic linking
Makefile:413: target 'out/src/third_party/lua-5.1.5/src' given more than once in the same rule
cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -DOPENSSL_API_1_1 -DLUA_VERSION_MAKEFILE=501 -Isrc/third_party/lua-5.1.5/src -DLUA_COMPAT_ALL -DUSE_LUA -DLUA_USE_POSIX -DLUA_USE_DLOPEN -Isrc/third_party -DUSE_LUA_FILE_SYSTEM -DUSE_ZLIB -DUSE_WEBSOCKET -DUSE_SERVER_STATS -fPIC src/civetweb.c -o out/src/civetweb.o
In file included from src/civetweb.c:12641:
src/mod_lua.inl: In function ‘lsp_response_send’:
src/mod_lua.inl:2264:6: warning: unused variable ‘num_args’ [-Wunused-variable]
 2264 |  int num_args = lua_gettop(L);
      |      ^~~~~~~~
In file included from src/civetweb.c:12641:
src/mod_lua.inl: In function ‘lsp_mg_gc’:
src/mod_lua.inl:2591:18: warning: implicit declaration of function ‘lua_tounsigned’ [-Wimplicit-function-declaration]
 2591 |  context_flags = lua_tounsigned(L, -1);
      |                  ^~~~~~~~~~~~~~
src/mod_lua.inl: In function ‘prepare_lua_environment’:
src/mod_lua.inl:2681:2: warning: implicit declaration of function ‘lua_pushunsigned’; did you mean ‘lua_pushinteger’? [-Wimplicit-function-declaration]
 2681 |  lua_pushunsigned(L, (unsigned)lua_context_flags);
      |  ^~~~~~~~~~~~~~~~
      |  lua_pushinteger
In file included from src/civetweb.c:12641:
src/mod_lua.inl: In function ‘lsp_response_send’:
src/mod_lua.inl:2317:15: warning: ‘retadd’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 2317 |   if ((retadd != 0) && (ret2 == 0)) {
      |       ~~~~~~~~^~~~~
cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -DOPENSSL_API_1_1 -DLUA_VERSION_MAKEFILE=501 -Isrc/third_party/lua-5.1.5/src -DLUA_COMPAT_ALL -DUSE_LUA -DLUA_USE_POSIX -DLUA_USE_DLOPEN -Isrc/third_party -DUSE_LUA_FILE_SYSTEM -DUSE_ZLIB -DUSE_WEBSOCKET -DUSE_SERVER_STATS src/main.c -o out/src/main.o
cc -o civetweb -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -DOPENSSL_API_1_1 -DLUA_VERSION_MAKEFILE=501 -Isrc/third_party/lua-5.1.5/src -DLUA_COMPAT_ALL -DUSE_LUA -DLUA_USE_POSIX -DLUA_USE_DLOPEN -Isrc/third_party -DUSE_LUA_FILE_SYSTEM -DUSE_ZLIB -DUSE_WEBSOCKET -DUSE_SERVER_STATS  out/src/civetweb.o out/src/main.o out/src/third_party/lfs.o  -lpthread -lm -lz -lrt -ldl -llua5.1
/usr/bin/ld: out/src/civetweb.o: in function `lsp_mg_gc':
civetweb.c:(.text+0x30cb): undefined reference to `lua_tounsigned'
/usr/bin/ld: out/src/civetweb.o: in function `prepare_lua_environment':
civetweb.c:(.text+0x9ba0): undefined reference to `lua_pushunsigned'
collect2: error: ld returned 1 exit status
make: *** [Makefile:406: civetweb] Error 1
```

**Comment by bel2125** [comment]
Lua 5.1 is deprecated, since support for Lua 5.4 has been added.
This means, it's no longer tested.

But this seams easy to fix: lua_tounsigned and lua_pushunsigned are just lua_tonumber and lua_pushnumber with a cast from/to unsigned. We can just add these definitions.
