### PR TITLE
build: change default worker thread stack size from 100 KB to system default

### PR DESCRIPTION
**Pull request by morgonf**
## Problem

Both build systems default every worker thread to a **100 KB** stack:

- `CMakeLists.txt`: `CIVETWEB_THREAD_STACK_SIZE` defaults to `102400`
- `Makefile`: `USE_STACK_SIZE ?= 102400` (since 2014, commit 407d2c9e)

This contradicts the documented behaviour. `docs/Embedding.md` ("Stack Sizes") states that *CivetWeb will use the default stack size on those systems (typically 1 MB per Windows, up to 8 MB for Linux)*, and `docs/Building.md` describes `USE_STACK_SIZE` as *"define stack size instead of using system default"*. The Zephyr path in `CMakeLists.txt` already sets the size to `0`.

100 KB is not enough for deeply nested request-handling call chains (e.g. `handle_static_file_request` + `mg_vprintf` + TLS), and it gets worse with hardening compiler options that enlarge stack frames. The result is a `SIGSEGV` inside a worker thread with no indication that the stack limit is the cause.

## Fix

Set the default to `0` in both `CMakeLists.txt` and the `Makefile`. `src/civetweb.c` already treats `USE_STACK_SIZE <= 1` as "do not call `pthread_attr_setstacksize()`", so the OS default applies.

The override path is unchanged: embedded users can still limit the stack with `-DCIVETWEB_THREAD_STACK_SIZE=<n>` or `make USE_STACK_SIZE=<n>`.

## Test plan

- [x] `make lib` with the default: compiler command line contains `-DUSE_STACK_SIZE=0`, build succeeds.
- [x] `make lib USE_STACK_SIZE=16384`: override still reaches the compiler.
- [x] CMake build with the default: unit tests pass (CI on the fork).

Note: upstream `master` currently does not compile (see #1392 / #1412), so the CI failure here is unrelated to this change.

### CODE REVIEW

**Comment by morgonf** [comment]
The CI failures here are caused by a pre-existing compilation error in `master` introduced by commit 588860e (CVE-2025-55763): a missing parenthesis in the `if` condition and an undeclared variable `cl` in `get_request()`. This breaks all GCC and clang builds regardless of what a PR changes. PR #1399 fixes it.

**Comment by morgonf** [comment]
@DL6ER would you mind taking a look at this one as well, when you find a moment? Thanks a lot for reviewing the other two.

**Comment by vivanishin** [comment]
Note that, 
1. This fix aligns CMake code with the documentation; curretnly they disagree: _CivetWeb will use the default stack size on those system (typically 1 MB per Windows, up to 8 MB for Linux) - for each thread._ — [`docs/Embedding.md#L116`](https://github.com/civetweb/civetweb/blob/588860e30721bf5453b0440c390865a8e85dcae5/docs/Embedding.md#L116)
2. @morgonf , I think, `Makefile` should be patched accordingly; it still has [`USE_STACK_SIZE ?= 102400`](https://github.com/civetweb/civetweb/blob/588860e30721bf5453b0440c390865a8e85dcae5/Makefile#L43)

**Comment by morgonf** [comment]
@vivanishin Agreed on both points, thanks. Updated the PR: the Makefile default (`USE_STACK_SIZE ?= 102400`, there since 2014) is now `0` as well, so both build systems match `docs/Embedding.md`. The code already treats `USE_STACK_SIZE <= 1` as "system default", and `make USE_STACK_SIZE=<n>` still works for embedded targets. Commit message and PR description now carry the documentation argument.
